## Reanalysis of data to more accurately find out what is left is previous analysis that caused model to hallucinate or wrong output

In [ ]:
from datasets import load_dataset

dataset = load_dataset("umarbutler/better-cuad", split="train")

C:\Users\aksha\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
data = dataset.to_pandas()

In [8]:
data.head(1)

,Filename,Document Name,Document Name-Answer,Parties,Parties-Answer,Agreement Date,Agreement Date-Answer,Effective Date,Effective Date-Answer,Expiration Date,...,Liquidated Damages-Answer,Warranty Duration,Warranty Duration-Answer,Insurance,Insurance-Answer,Covenant Not To Sue,Covenant Not To Sue-Answer,Third Party Beneficiary,Third Party Beneficiary-Answer,Text
0,CybergyHoldingsInc_20140520_10-Q_EX-10.27_8605...,['MARKETING AFFILIATE AGREEMENT'],MARKETING AFFILIATE AGREEMENT,"['BIRCH FIRST GLOBAL INVESTMENTS INC.', 'MA', ...","Birch First Global Investments Inc. (""Company""...","['8th day of May 2014', 'May 8, 2014']",5/8/14,['This agreement shall begin upon the date of ...,NaN,['This agreement shall begin upon the date of ...,...,No,"[""COMPANY'S SOLE AND EXCLUSIVE LIABILITY FOR T...",Yes,[],No,[],No,[],No,Exhibit 10.27\n\nMARKETING AFFILIATE AGREEMENT...

In [9]:
data.shape

(510, 84)

In [10]:
data.columns

Index(['Filename', 'Document Name', 'Document Name-Answer', 'Parties',
       'Parties-Answer', 'Agreement Date', 'Agreement Date-Answer',
       'Effective Date', 'Effective Date-Answer', 'Expiration Date',
       'Expiration Date-Answer', 'Renewal Term', 'Renewal Term-Answer',
       'Notice Period To Terminate Renewal',
       'Notice Period To Terminate Renewal- Answer', 'Governing Law',
       'Governing Law-Answer', 'Most Favored Nation',
       'Most Favored Nation-Answer', 'Competitive Restriction Exception',
       'Competitive Restriction Exception-Answer', 'Non-Compete',
       'Non-Compete-Answer', 'Exclusivity', 'Exclusivity-Answer',
       'No-Solicit Of Customers', 'No-Solicit Of Customers-Answer',
       'No-Solicit Of Employees', 'No-Solicit Of Employees-Answer',
       'Non-Disparagement', 'Non-Disparagement-Answer',
       'Termination For Convenience', 'Termination For Convenience-Answer',
       'Rofr/Rofo/Rofn', 'Rofr/Rofo/Rofn-Answer', 'Change Of Control',
       'Change Of Control-Answer', 'Anti-Assignment', 'Anti-Assignment-Answer',
       'Revenue/Profit Sharing', 'Revenue/Profit Sharing-Answer',
       'Price Restrictions', 'Price Restrictions-Answer', 'Minimum Commitment',
       'Minimum Commitment-Answer', 'Volume Restriction',
       'Volume Restriction-Answer', 'Ip Ownership Assignment',
       'Ip Ownership Assignment-Answer', 'Joint Ip Ownership',
       'Joint Ip Ownership-Answer', 'License Grant', 'License Grant-Answer',
       'Non-Transferable License', 'Non-Transferable License-Answer',
       'Affiliate License-Licensor', 'Affiliate License-Licensor-Answer',
       'Affiliate License-Licensee', 'Affiliate License-Licensee-Answer',
       'Unlimited/All-You-Can-Eat-License',
       'Unlimited/All-You-Can-Eat-License-Answer',
       'Irrevocable Or Perpetual License',
       'Irrevocable Or Perpetual License-Answer', 'Source Code Escrow',
       'Source Code Escrow-Answer', 'Post-Termination Services',
       'Post-Termination Services-Answer', 'Audit Rights',
       'Audit Rights-Answer', 'Uncapped Liability',
       'Uncapped Liability-Answer', 'Cap On Liability',
       'Cap On Liability-Answer', 'Liquidated Damages',
       'Liquidated Damages-Answer', 'Warranty Duration',
       'Warranty Duration-Answer', 'Insurance', 'Insurance-Answer',
       'Covenant Not To Sue', 'Covenant Not To Sue-Answer',
       'Third Party Beneficiary', 'Third Party Beneficiary-Answer', 'Text'],
      dtype='str')

In [11]:
data = data.drop(columns='Filename')

In [17]:
data[['Document Name', 'Document Name-Answer']].sample(5)

,Document Name,Document Name-Answer
348,['Strategic Alliance Agreement'],Strategic Alliance Agreement
317,['NON COMPETITION AGREEMENT AND RIGHT OF FIRST...,NON COMPETITION AGREEMENT AND RIGHT OF FIRST O...
350,['Strategic Alliance Agreement'],Strategic Alliance Agreement
164,['MANUFACTURING AGREEMENT'],MANUFACTURING AGREEMENT
495,['SUPPLY AGREEMENT'],SUPPLY AGREEMENT

In [23]:
data[['Parties', 'Parties-Answer']].tail(30)

,Parties,Parties-Answer
480,"['(""SLD"")', 'American Champion Media, Inc.', '...","American Champion Media, (""ACM""); Shun Li De C..."
481,"['Sabco', 'SABCO RACING, INC.', 'Prolong', 'Pr...","SABCO RACING, INC. (""Sabco""); Prolong Super Lu..."
482,"['Excite', 'Excite, Inc.', 'NetGrocer, Inc.', ...","Excite, Inc. (""Excite""); NetGrocer, Inc.(""NetG..."
483,"['the ""Sponsor""', 'C.M. OLIVER & COMPANY LIMIT...","HEALTHCARE CAPITAL CORP. (""Issue""); C.M. OLIVE..."
484,"['SAN DIEGO BALLPARK FUNDING LLC SPONSOR', ""Ru...",SAN DIEGO BALLPARK FUNDING LLC; Rubio's Fresh ...
485,"['Tickets', 'MP3.com, Inc.,', 'MP3.com', 'Tick...","Tickets.com Inc. ""Tickets""; MP3.com Inc. ""MP3...."
486,"['ANTHEMIC', 'ANTHEMIC, LLC', 'Sponsor""', 'VNU...","ANTHEMIC, LLC (""ANTHEMIC""); VNUE INC (the ""Spo..."
487,"['PivX', 'Detto Technologies', 'Detto', 'PivX ...","PivX Corporation (""PivX""); Detto Technologies ..."
488,"['2205925 Ontario Limited', 'Diversinet', 'Div...","Diversinet Corp. (""Diversinet""); 2205925 Ontar..."
489,"['TouchStar', 'Reseller', 'WORLDWIDE STRATEGIE...","Touchstar Software Corporation (""TouchStar""); ..."
490,"['""Supplier"" or ""Fonterra""', 'Fonterra (USA) I...","Premier Nutrition Company, LLC, (""Buyer"" or ""P..."
491,"['CUTANEA', 'Ferrer Internacional, S.A.', 'Cut...","Cutanea Life Sciences, Inc. (""CUTANEA""); Ferre..."
492,"['CPDC', 'Centre for Probe Development and Com...",Centre for Probe Development and Commercializa...
493,"['HOVIONE INTER AG', 'INTERSECT ENT, Inc.', 'O...","HOVIONE INTER AG (""HOVIONE""); INTERSECT ENT, I..."
494,"['Ultragenyx Pharmaceutical Inc', 'Cremer', 'U...","Cremer Oleo GmbH & Co KG (""Cremer""); Ultrageny..."
495,['SutroVax and Sutro may be referred to herein...,"SutroVax, Inc. (""SutroVax""); Sutro Biopharma, ..."
496,"['Vericel Corporation', 'Vericel and MediWound...","Vericel Corporation (""Vericel""); MediWound Ltd..."
497,"['""the Owner""', 'the Licensee', 'NCC ESCROW IN...","NCC ESCROW INTERNATIONAL LIMITED (""NCC"")"
498,"['Cargill', 'Cargill, Incorporated', 'BioAmber...","Cargill, Incorporated (“Cargill”); BioAmber S...."
499,"['Blackwell', 'Munksgaard', 'together, Blackwe...","HealthGate Data Corp. (""HealthGate""); Blackwel..."
500,"['Cargill, Incorporated', 'Bioamber and Cargil...","Cargill, Incorporated (""Cargill""); Bioamber S...."
501,"['Distributor', 'Ingram Micro', 'NETGEAR, Inc....","Ingram Micro (""Distributor""); NETGEAR, Inc. (""..."
502,"['Distributor', 'Ingram Micro', 'NETGEAR, Inc....","Ingram Micro (""Distributor""); NETGEAR, Inc. (""..."
503,"['Vendor', 'NETGEAR, INC.', 'Ingram', 'INGRAM ...","Ingram Micro (""Distributor""); NETGEAR, Inc. (""..."
504,"['Peregrine/Bridge Transfer Corporation', 'Lic...","Peregrine/Bridge Transfer Corporation (""Licens..."
505,"['Peregrine/Bridge Transfer Corporation', 'Lic...","Peregrine/Bridge Transfer Corporation (""Licens..."
506,"['SQUARE TWO GOLF INC.', 'KATHY WHITWORTH', 't...","SQUARE TWO GOLF INC. (""Company""); KATHY WHITWO..."
507,"['SQUARE TWO GOLF INC.', 'Recipient', 'KATHY W...","SQUARE TWO GOLF INC. (""Company""); KATHY WHITWO..."
508,"['The Associated Press', 'Kubient', 'Customer'...","Kubient, Inc. (""Kubient""); The Associated Pres..."
509,"['the ""Customer""', 'Kubient Inc.', 'Kubient', ...","Kubient Inc. (""Kubient""); The Associated Press..."

In [ ]:
data[['Parties', 'Parties-Answer']].sample(10)

,Parties,Parties-Answer
391,"['NMS COMMUNICATIONS CORP.', 'VERSO BACKHAUL S...","NMS Communications Corp. (""Seller""); Verson Ba..."
47,"['the Customer', 'ESPACIO INFORMATION TECHNOLO...","SLICON SMELTERS PTY LTD (""Customer""); ESPACIO ..."
97,"['Digital Cinema Destinations Corp.', '""Networ...","National CineMedia, LLC (“NCM”); Digital Cinem..."
224,"['FNW', 'Sponsor', 'FOOTBALL NORTHWEST LLC', '...","Football Northwest LLC, (""FNW""); Mercata, Inc...."
206,"['[•]', 'Service Recipient', 'Rise (Tianjin) E...",Rise (Tianjin) Education Information Consultin...
331,"['Physician Sales & Service, Inc.', 'PSS', 'Gu...","Gulf South Medical Supply, Inc. (""GSMS""); Phys..."
362,"['Sucampo Pharmaceuticals, Inc.', 'R-Tech Ueno...","R-Tech Ueno, Ltd. (""Company""); Sucampo Pharma,..."
76,"['Palmer Square Capital Management LLC', 'the ...","Palmer Square Capital Management LLC (""Licenso..."
149,['Fox and Licensee are collectively referred t...,Twentieth Century Fox Licensing & Merchandisin...
173,"['Medalist Diversified REIT, Inc.', 'Gunston C...","Gunston Consulting, LLC (""CONSULTANT""); Medali..."

In [19]:
data[['Governing Law', 'Governing Law-Answer']].sample(5)

,Governing Law,Governing Law-Answer
452,"['Accordingly, the parties agree that the val...",New York
35,"[""The laws of the State of New York (excluding...",New York
237,['Any lawsuit relating to any matter arising u...,Massachusetts; Netherlands
461,['This Agreement shall be interpreted in accor...,Indiana
138,"['This Agreement, the rights and obligations o...",New York

In [26]:
data[['Non-Compete', 'Non-Compete-Answer']].sample(20)

                                           Non-Compete Non-Compete-Answer
493                                                 []                 No
29                                                  []                 No
25                                                  []                 No
385                                                 []                 No
217                                                 []                 No
46   ['Throughout the Term and for a period of six ...                Yes
342                                                 []                 No
391                                                 []                 No
424  ['You must:<omitted>5.1.15 not become a Compet...                Yes
258                                                 []                 No
245                                                 []                 No
180                                                 []                 No
57   ['For so long as the appointment set out in Se...                Yes
145                                                 []                 No
458                                                 []                 No
482  ['For the purposes of this Agreement, "Competi...                Yes
462                                                 []                 No
191                                                 []                 No
419  ['In addition, in the event that Array termina...                Yes
289  ['During the Term, neither Company nor any of ...                Yes

In [29]:
print(data.isnull().sum().to_string())

Document Name                                   0
Document Name-Answer                            0
Parties                                         0
Parties-Answer                                  1
Agreement Date                                  0
Agreement Date-Answer                          45
Effective Date                                  0
Effective Date-Answer                         151
Expiration Date                                 0
Expiration Date-Answer                        181
Renewal Term                                    0
Renewal Term-Answer                           347
Notice Period To Terminate Renewal              0
Notice Period To Terminate Renewal- Answer    409
Governing Law                                   0
Governing Law-Answer                           76
Most Favored Nation                             0
Most Favored Nation-Answer                      0
Competitive Restriction Exception               0
Competitive Restriction Exception-Answer        0
Non-Compete                                     0
Non-Compete-Answer                              0
Exclusivity                                     0
Exclusivity-Answer                              0
No-Solicit Of Customers                         0
No-Solicit Of Customers-Answer                  0
No-Solicit Of Employees                         0
No-Solicit Of Employees-Answer                  0
Non-Disparagement                               0
Non-Disparagement-Answer                        0
Termination For Convenience                     0
Termination For Convenience-Answer              0
Rofr/Rofo/Rofn                                  0
Rofr/Rofo/Rofn-Answer                           0
Change Of Control                               0
Change Of Control-Answer                        0
Anti-Assignment                                 0
Anti-Assignment-Answer                          0
Revenue/Profit Sharing                          0
Revenue/Profit Sharing-Answer                   0
Price Restrictions                              0
Price Restrictions-Answer                       0
Minimum Commitment                              0
Minimum Commitment-Answer                       0
Volume Restriction                              0
Volume Restriction-Answer                       0
Ip Ownership Assignment                         0
Ip Ownership Assignment-Answer                  0
Joint Ip Ownership                              0
Joint Ip Ownership-Answer                       0
License Grant                                   0
License Grant-Answer                            0
Non-Transferable License                        0
Non-Transferable License-Answer                 0
Affiliate License-Licensor                      0
Affiliate License-Licensor-Answer               0
Affiliate License-Licensee                      0
Affiliate License-Licensee-Answer               0
Unlimited/All-You-Can-Eat-License               0
Unlimited/All-You-Can-Eat-License-Answer        0
Irrevocable Or Perpetual License                0
Irrevocable Or Perpetual License-Answer         0
Source Code Escrow                              0
Source Code Escrow-Answer                       0
Post-Termination Services                       0
Post-Termination Services-Answer                0
Audit Rights                                    0
Audit Rights-Answer                             0
Uncapped Liability                              0
Uncapped Liability-Answer                       0
Cap On Liability                                0
Cap On Liability-Answer                         0
Liquidated Damages                              0
Liquidated Damages-Answer                       0
Warranty Duration                               0
Warranty Duration-Answer                        0
Insurance                                       0
Insurance-Answer                                0
Covenant Not To Sue                             0
Covenant Not To Sue-Answer                      0
Third Party Beneficiary                         0
Third Party Beneficiary-Answer                  0
Text                                            0

    Trying to remove some noisy data we don't require for the purpose

In [30]:
data = data.drop(columns=['Renewal Term','Renewal Term-Answer','Notice Period To Terminate Renewal','Notice Period To Terminate Renewal- Answer'])

    Making null values as 'Not found' so model don't break during fine tuning but also do not hallucinate that there can be null values possible

In [31]:
null_value_cols = ['Parties-Answer', 'Agreement Date-Answer', 'Governing Law-Answer', 'Effective Date-Answer', 'Expiration Date-Answer']

fill_dict = {col: 'Not found' for col in null_value_cols}

data = data.fillna(value=fill_dict)

In [33]:
print(data.isnull().sum().to_string())

Document Name                               0
Document Name-Answer                        0
Parties                                     0
Parties-Answer                              0
Agreement Date                              0
Agreement Date-Answer                       0
Effective Date                              0
Effective Date-Answer                       0
Expiration Date                             0
Expiration Date-Answer                      0
Governing Law                               0
Governing Law-Answer                        0
Most Favored Nation                         0
Most Favored Nation-Answer                  0
Competitive Restriction Exception           0
Competitive Restriction Exception-Answer    0
Non-Compete                                 0
Non-Compete-Answer                          0
Exclusivity                                 0
Exclusivity-Answer                          0
No-Solicit Of Customers                     0
No-Solicit Of Customers-Answer              0
No-Solicit Of Employees                     0
No-Solicit Of Employees-Answer              0
Non-Disparagement                           0
Non-Disparagement-Answer                    0
Termination For Convenience                 0
Termination For Convenience-Answer          0
Rofr/Rofo/Rofn                              0
Rofr/Rofo/Rofn-Answer                       0
Change Of Control                           0
Change Of Control-Answer                    0
Anti-Assignment                             0
Anti-Assignment-Answer                      0
Revenue/Profit Sharing                      0
Revenue/Profit Sharing-Answer               0
Price Restrictions                          0
Price Restrictions-Answer                   0
Minimum Commitment                          0
Minimum Commitment-Answer                   0
Volume Restriction                          0
Volume Restriction-Answer                   0
Ip Ownership Assignment                     0
Ip Ownership Assignment-Answer              0
Joint Ip Ownership                          0
Joint Ip Ownership-Answer                   0
License Grant                               0
License Grant-Answer                        0
Non-Transferable License                    0
Non-Transferable License-Answer             0
Affiliate License-Licensor                  0
Affiliate License-Licensor-Answer           0
Affiliate License-Licensee                  0
Affiliate License-Licensee-Answer           0
Unlimited/All-You-Can-Eat-License           0
Unlimited/All-You-Can-Eat-License-Answer    0
Irrevocable Or Perpetual License            0
Irrevocable Or Perpetual License-Answer     0
Source Code Escrow                          0
Source Code Escrow-Answer                   0
Post-Termination Services                   0
Post-Termination Services-Answer            0
Audit Rights                                0
Audit Rights-Answer                         0
Uncapped Liability                          0
Uncapped Liability-Answer                   0
Cap On Liability                            0
Cap On Liability-Answer                     0
Liquidated Damages                          0
Liquidated Damages-Answer                   0
Warranty Duration                           0
Warranty Duration-Answer                    0
Insurance                                   0
Insurance-Answer                            0
Covenant Not To Sue                         0
Covenant Not To Sue-Answer                  0
Third Party Beneficiary                     0
Third Party Beneficiary-Answer              0
Text                                        0

    Droping all the question columns that has no use in fine tuning

In [35]:
cols_to_drop = ['Document Name', 'Parties', 'Agreement Date', 'Effective Date', 'Expiration Date', 'Governing Law', 'Most Favored Nation', 'Competitive Restriction Exception', 'Non-Compete', 'Exclusivity', 'No-Solicit Of Customers', 'No-Solicit Of Employees', 'Non-Disparagement', 'Termination For Convenience', 'Rofr/Rofo/Rofn', 'Change Of Control', 'Anti-Assignment', 'Revenue/Profit Sharing', 'Price Restrictions', 'Minimum Commitment', 'Volume Restriction', 'Ip Ownership Assignment', 'Joint Ip Ownership', 'License Grant', 'Non-Transferable License', 'Affiliate License-Licensor', 'Affiliate License-Licensee', 'Unlimited/All-You-Can-Eat-License', 'Irrevocable Or Perpetual License', 'Source Code Escrow', 'Post-Termination Services', 'Audit Rights', 'Uncapped Liability', 'Cap On Liability', 'Liquidated Damages', 'Warranty Duration', 'Insurance', 'Covenant Not To Sue', 'Third Party Beneficiary']

data = data.drop(columns=cols_to_drop)

In [39]:
data.columns

Index(['Document Name-Answer', 'Parties-Answer', 'Agreement Date-Answer',
       'Effective Date-Answer', 'Expiration Date-Answer',
       'Governing Law-Answer', 'Most Favored Nation-Answer',
       'Competitive Restriction Exception-Answer', 'Non-Compete-Answer',
       'Exclusivity-Answer', 'No-Solicit Of Customers-Answer',
       'No-Solicit Of Employees-Answer', 'Non-Disparagement-Answer',
       'Termination For Convenience-Answer', 'Rofr/Rofo/Rofn-Answer',
       'Change Of Control-Answer', 'Anti-Assignment-Answer',
       'Revenue/Profit Sharing-Answer', 'Price Restrictions-Answer',
       'Minimum Commitment-Answer', 'Volume Restriction-Answer',
       'Ip Ownership Assignment-Answer', 'Joint Ip Ownership-Answer',
       'License Grant-Answer', 'Non-Transferable License-Answer',
       'Affiliate License-Licensor-Answer',
       'Affiliate License-Licensee-Answer',
       'Unlimited/All-You-Can-Eat-License-Answer',
       'Irrevocable Or Perpetual License-Answer', 'Source Code Escrow-Answer',
       'Post-Termination Services-Answer', 'Audit Rights-Answer',
       'Uncapped Liability-Answer', 'Cap On Liability-Answer',
       'Liquidated Damages-Answer', 'Warranty Duration-Answer',
       'Insurance-Answer', 'Covenant Not To Sue-Answer',
       'Third Party Beneficiary-Answer', 'Text'],
      dtype='str')

    Striping answer from last so model to misunderstand

In [40]:
data.columns = data.columns.str.strip().str.removesuffix('-Answer')

print(data.columns)

Index(['Document Name', 'Parties', 'Agreement Date', 'Effective Date',
       'Expiration Date', 'Governing Law', 'Most Favored Nation',
       'Competitive Restriction Exception', 'Non-Compete', 'Exclusivity',
       'No-Solicit Of Customers', 'No-Solicit Of Employees',
       'Non-Disparagement', 'Termination For Convenience', 'Rofr/Rofo/Rofn',
       'Change Of Control', 'Anti-Assignment', 'Revenue/Profit Sharing',
       'Price Restrictions', 'Minimum Commitment', 'Volume Restriction',
       'Ip Ownership Assignment', 'Joint Ip Ownership', 'License Grant',
       'Non-Transferable License', 'Affiliate License-Licensor',
       'Affiliate License-Licensee', 'Unlimited/All-You-Can-Eat-License',
       'Irrevocable Or Perpetual License', 'Source Code Escrow',
       'Post-Termination Services', 'Audit Rights', 'Uncapped Liability',
       'Cap On Liability', 'Liquidated Damages', 'Warranty Duration',
       'Insurance', 'Covenant Not To Sue', 'Third Party Beneficiary', 'Text'],
      dtype='str')

In [41]:
data.shape

(510, 40)

    Drop columns which is not much useful and create problem for model

In [47]:
cols_not_needed = ['Source Code Escrow', 'Rofr/Rofo/Rofn', 'Covenant Not To Sue', 'Joint Ip Ownership', 'Most Favored Nation', 'Competitive Restriction Exception', 'Third Party Beneficiary', 'Non-Transferable License', 'Affiliate License-Licensor', 'Affiliate License-Licensee', 'Unlimited/All-You-Can-Eat-License', 'Irrevocable Or Perpetual License', 'Minimum Commitment', 'Volume Restriction']

data = data.drop(columns=cols_not_needed)

In [48]:
print(data.shape)
data.columns

(510, 26)

Index(['Document Name', 'Parties', 'Agreement Date', 'Effective Date',
       'Expiration Date', 'Governing Law', 'Non-Compete', 'Exclusivity',
       'No-Solicit Of Customers', 'No-Solicit Of Employees',
       'Non-Disparagement', 'Termination For Convenience', 'Change Of Control',
       'Anti-Assignment', 'Revenue/Profit Sharing', 'Price Restrictions',
       'Ip Ownership Assignment', 'License Grant', 'Post-Termination Services',
       'Audit Rights', 'Uncapped Liability', 'Cap On Liability',
       'Liquidated Damages', 'Warranty Duration', 'Insurance', 'Text'],
      dtype='str')

    Analysing the left 26 columns

In [49]:
for col in data.columns:
    print(f'''
    Column Name: {col}
    Column Sample Values:
    {data[col].sample(5)}
    ''')

    Column Name: Document Name
    Column Sample Values:
    369                              COLLABORATION AGREEMENT
406                                DISTRIBUTOR AGREEMENT
24     Website Design, Development and Hosting Agreement
257                                     SUPPLY AGREEMENT
209                                    SERVICE AGREEMENT
Name: Document Name, dtype: str


    Column Name: Parties
    Column Sample Values:
    155    ABG-Shaq, LLC ("ABG"); Papa John's Marketing F...
193    Nationwide Fund Management LLC ("Nationwide");...
75     New Mountain Capital, LLC. ("Licensor"); NMF S...
280    Collectible Concepts Group, Inc. ("CCGI"); Piv...
492    Centre for Probe Development and Commercializa...
Name: Parties, dtype: str


    Column Name: Agreement Date
    Column Sample Values:
    44       12/20/18
288       2/10/12
376       4/29/10
335    11/[]/2006
220       3/11/99
Name: Agreement Date, dtype: str


    Column Name: Effective Date
    Column Sample Values:
    134    []/[]/2015
493       1/20/20
163     Not found
46       11/12/18
33       12/17/19
Name: Effective Date, dtype: str


    Column Name: Expiration Date
    Column Sample Values:
    256     Not found
113    []/[]/2022
407     perpetual
87      Not found
210     perpetual
Name: Expiration Date, dtype: str


    Column Name: Governing Law
    Column Sample Values:
    279    Not found
194     New York
349     New York
208    Not found
368     Delaware
Name: Governing Law, dtype: str


    Column Name: Non-Compete
    Column Sample Values:
    332     No
211     No
274     No
407     No
365    Yes
Name: Non-Compete, dtype: str


    Column Name: Exclusivity
    Column Sample Values:
    248    Yes
466     No
382     No
110    Yes
154     No
Name: Exclusivity, dtype: str


    Column Name: No-Solicit Of Customers
    Column Sample Values:
    243    No
155    No
451    No
278    No
496    No
Name: No-Solicit Of Customers, dtype: str


    Column Name: No-Solicit Of Employees
    Column Sample Values:
    240    No
367    No
399    No
57     No
45     No
Name: No-Solicit Of Employees, dtype: str


    Column Name: Non-Disparagement
    Column Sample Values:
    18     No
468    No
340    No
220    No
439    No
Name: Non-Disparagement, dtype: str


    Column Name: Termination For Convenience
    Column Sample Values:
    187     No
478     No
76     Yes
282     No
45      No
Name: Termination For Convenience, dtype: str


    Column Name: Change Of Control
    Column Sample Values:
    135    No
231    No
388    No
294    No
488    No
Name: Change Of Control, dtype: str


    Column Name: Anti-Assignment
    Column Sample Values:
    264    Yes
509    Yes
81     Yes
66     Yes
285    Yes
Name: Anti-Assignment, dtype: str


    Column Name: Revenue/Profit Sharing
    Column Sample Values:
    415     No
74      No
390     No
210    Yes
151    Yes
Name: Revenue/Profit Sharing, dtype: str


    Column Name: Price Restrictions
    Column Sample Values:
    15     Yes
409     No
232    Yes
404     No
303     No
Name: Price Restrictions, dtype: str


    Column Name: Ip Ownership Assignment
    Column Sample Values:
    81     Yes
470     No
183    Yes
330     No
401     No
Name: Ip Ownership Assignment, dtype: str


    Column Name: License Grant
    Column Sample Values:
    12     Yes
48      No
384    Yes
15      No
4      Yes
Name: License Grant, dtype: str


    Column Name: Post-Termination Services
    Column Sample Values:
    378    Yes
115     No
171     No
319    Yes
478    Yes
Name: Post-Termination Services, dtype: str


    Column Name: Audit Rights
    Column Sample Values:
    106     No
57     Yes
360    Yes
485     No
322    Yes
Name: Audit Rights, dtype: str


    Column Name: Uncapped Liability
    Column Sample Values:
    478    No
507    No
55     No
498    No
139    No
Name: Uncapped Liability, dtype: str


    Column Name: Cap On Liability
    Column Sample Values:
    9      Yes
354     No
171     No
57     Yes
278    Yes
Name: Cap On Liability, dtype: str


    Column Name: Liquidated Damages
    Column Sample Values:
    89     No
471    No
492    No
102    No
150    No
Name: Liquidated Damages, dtype: str


    Column Name: Warranty Duration
    Column Sample Values:
    2       No
398    Yes
166     No
272     No
131     No
Name: Warranty Duration, dtype: str


    Column Name: Insurance
    Column Sample Values:
    160    Yes
274     No
24      No
404    Yes
381    Yes
Name: Insurance, dtype: str


    Column Name: Text
    Column Sample Values:
    66     SPONSORSHIP AGREEMENT This agreement (the "Agr...
501    term under the Agreement will not be effective...
131    Exhibit 10.19 JOINT CONTENT LICENSE AGREEMENT ...
417    EXHIBIT 10.12\n\n                             ...
431    1\n\n                                         ...
Name: Text, dtype: str

    Keeping most useful columns & also removing the boolean columns

In [51]:
columns_to_keep = [
    'Document Name', 
    'Parties', 
    'Agreement Date', 
    'Effective Date', 
    'Expiration Date', 
    'Governing Law', 
    'Text'
]

data = data[columns_to_keep]

print("Final Training Columns:\n", data.columns)

Final Training Columns:
 Index(['Document Name', 'Parties', 'Agreement Date', 'Effective Date',
       'Expiration Date', 'Governing Law', 'Text'],
      dtype='str')

In [52]:
for col in data.columns:
    print(f'''
    Column Name: {col}
    Column Sample Values:
    {data[col].sample(5)}
    ''')

    Column Name: Document Name
    Column Sample Values:
    322                               JOINT VENTURE CONTRACT
323            NON-COMPETITION AGREEMENT AMENDMENT NO. 1
507    Intellectual Property Rights                 C...
449                 OPERATIONS AND MAINTENANCE AGREEMENT
47                                 OUTSOURCING AGREEMENT
Name: Document Name, dtype: str


    Column Name: Parties
    Column Sample Values:
    117    Bioeq IP, AG ("Bioeq"); Coherus BioSciences, I...
168    Slinger Bag Inc. (the "Company"); Aitan Zachar...
57     EHAVE, INC. ("Ehave"); COMPANION HEALTHCARE TE...
295    Bank of America Corporatino, Banc of America P...
248    AZUL LINHAS AÉREAS BRASILEIRAS S/A ("Company",...
Name: Parties, dtype: str


    Column Name: Agreement Date
    Column Sample Values:
    437    12/22/17
314      3/1/16
393     3/31/00
372      7/1/20
110     2/20/12
Name: Agreement Date, dtype: str


    Column Name: Effective Date
    Column Sample Values:
    238    Not found
116      3/20/20
329       4/2/20
343      9/23/16
130    Not found
Name: Effective Date, dtype: str


    Column Name: Expiration Date
    Column Sample Values:
    416    Not found
167     12/31/21
163    Not found
393      3/31/05
376       8/1/14
Name: Expiration Date, dtype: str


    Column Name: Governing Law
    Column Sample Values:
    152    Not found
340     New York
246      Florida
202     Colorado
466    Not found
Name: Governing Law, dtype: str


    Column Name: Text
    Column Sample Values:
    383    Exhibit 10.20\n\nPages where confidential trea...
285    Exhibit 2.01   Strategic Alliance Agreement   ...
166    AMENDMENT NO. 3 TO STREMICK'S HERITAGE FOODS, ...
143    Exhibit 10.39\n\nIN ACCORDANCE WITH ITEM 601(b...
26     Exhibit 10.2     SERVICES AND HOSTING AGREEMEN...
Name: Text, dtype: str

- Here we analyse & identified the columns that need for fine tuning the model and ignoring the once which either no need to can be problematic